
import os


def set_device_capability_in_os_envs(dev_info):
    if dev_info == "hp-elitedesk-800-g6":
        os.environ["CPU_SIMD128_REGISTERS"] = "16"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "32768"
        os.environ["GPU_MAX_L1_CACHE_SIZE"] = "32768"
        os.environ["GPU_REGISTERS_PER_THREAD"] = "1024"
        os.environ["GPU_REGISTERS_PER_BLOCK"] = "57344"
        os.environ["GPU_REGISTERS_PER_PROCESSOR"] = "57344"
        os.environ["GPU_WARP_SIZE"] = "-1"
        os.environ["GPU_MAX_ACTIVE_WARPS"] = "-1"
        os.environ["GPU_MAX_THREADS_PER_BLOCK"] = "65536"
        os.environ["GPU_MAX_BLOCKS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_MAX_PROCESSORS"] = "3"
        os.environ["GPU_EXECUTION_MODEL"] = "SIMD"
        os.environ["GPU_SHARED_MEMORY_LEVEL"] = "1"
    elif dev_info == "honor-magicbook-16":
        os.environ["CPU_SIMD128_REGISTERS"] = "16"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "32768"
        os.environ["GPU_MAX_L1_CACHE_SIZE"] = "131072"
        os.environ["GPU_REGISTERS_PER_THREAD"] = "255"
        os.environ["GPU_REGISTERS_PER_BLOCK"] = "65536"
        os.environ["GPU_REGISTERS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_WARP_SIZE"] = "32"
        os.environ["GPU_MAX_ACTIVE_WARPS"] = "48"
        os.environ["GPU_MAX_THREADS_PER_BLOCK"] = "1536"
        os.environ["GPU_MAX_BLOCKS_PER_PROCESSOR"] = "16"
        os.environ["GPU_MAX_PROCESSORS"] = "16"
        os.environ["GPU_EXECUTION_MODEL"] = "SIMT"
        os.environ["GPU_SHARED_MEMORY_LEVEL"] = "1"
    elif dev_info == "honor-magicbook-17-amd":
        os.environ["CPU_SIMD128_REGISTERS"] = "16"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "32768"
        os.environ["GPU_MAX_L1_CACHE_SIZE"] = "131072"
        os.environ["GPU_REGISTERS_PER_THREAD"] = "1024"
        os.environ["GPU_REGISTERS_PER_BLOCK"] = "65536"
        os.environ["GPU_REGISTERS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_WARP_SIZE"] = "-1"
        os.environ["GPU_MAX_ACTIVE_WARPS"] = "-1"
        os.environ["GPU_MAX_THREADS_PER_BLOCK"] = "65536"
        os.environ["GPU_MAX_BLOCKS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_MAX_PROCESSORS"] = "8"
        os.environ["GPU_EXECUTION_MODEL"] = "SIMT"
        os.environ["GPU_SHARED_MEMORY_LEVEL"] = "1"
    elif dev_info == "surface-book-4":
        os.environ["CPU_SIMD128_REGISTERS"] = "16"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "32768"
        os.environ["GPU_MAX_L1_CACHE_SIZE"] = "65536"
        os.environ["GPU_REGISTERS_PER_THREAD"] = "255"
        os.environ["GPU_REGISTERS_PER_BLOCK"] = "65536"
        os.environ["GPU_REGISTERS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_WARP_SIZE"] = "32"
        os.environ["GPU_MAX_ACTIVE_WARPS"] = "32"
        os.environ["GPU_MAX_THREADS_PER_BLOCK"] = "1024"
        os.environ["GPU_MAX_BLOCKS_PER_PROCESSOR"] = "16"
        os.environ["GPU_MAX_PROCESSORS"] = "30"
        os.environ["GPU_EXECUTION_MODEL"] = "SIMT"
        os.environ["GPU_SHARED_MEMORY_LEVEL"] = "1"
    elif dev_info in ["pixel-4-xl", "vivo-x30", "honor-70", "mate-20"]:
        os.environ["CPU_SIMD128_REGISTERS"] = "32"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "-1"
    else:
        os.environ["CPU_SIMD128_REGISTERS"] = "32"
        os.environ["CPU_MAX_L1_CACHE_SIZE"] = "65536"
        # CUDA Compute Capability 8.6
        os.environ["GPU_MAX_L1_CACHE_SIZE"] = "131072"
        os.environ["GPU_REGISTERS_PER_THREAD"] = "255"
        os.environ["GPU_REGISTERS_PER_BLOCK"] = "65536"
        os.environ["GPU_REGISTERS_PER_PROCESSOR"] = "65536"
        os.environ["GPU_WARP_SIZE"] = "32"
        os.environ["GPU_MAX_ACTIVE_WARPS"] = "48"
        os.environ["GPU_MAX_THREADS_PER_BLOCK"] = "1536"
        os.environ["GPU_MAX_BLOCKS_PER_PROCESSOR"] = "16"
        os.environ["GPU_MAX_PROCESSORS"] = "68"
        os.environ["GPU_EXECUTION_MODEL"] = "SIMT"
        os.environ["GPU_SHARED_MEMORY_LEVEL"] = "1"
