
macro(find_binaryen use_binaryen)
  set(__use_binaryen ${use_binaryen})
  if(IS_DIRECTORY ${__use_binaryen})
    set(__binaryen_sdk ${__use_binaryen})
  elseif(IS_DIRECTORY $ENV{BINARIEN_SDK})
    set(__binaryen_sdk $ENV{BINARIEN_SDK})
  else()
    set(__binaryen_sdk "")
  endif()

  if(__binaryen_sdk)
    set(Binaryen_INCLUDE_DIRS ${__binaryen_sdk}/src)
    find_library(Binaryen_LIBRARY NAMES binaryen binaryen-1 PATHS ${__binaryen_sdk}/lib)
    if(Binaryen_LIBRARY)
      set(Binaryen_FOUND TRUE)
    endif()
  endif(__binaryen_sdk)
endmacro(find_binaryen)
